name: frontend
version: 0.1.0.0
synopsis: frontend client

category: Web

license: BSD3

author: <author>

# github: <GitHub Username>/<PackageName>

ghc-options: -Wall -fno-warn-unused-do-bind
ghcjs-options: -dedupe -DGHCJS_BROWSER -DGHCJS_GC_INTERVAL=30000000

# a set of default extensions that for pure development
default-extensions:
  - AutoDeriveTypeable
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyCase
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImplicitParams
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PatternSynonyms
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators
  - TypeSynonymInstances
  - ViewPatterns
  - TemplateHaskell

dependencies:
  - base
  - pure
  - pure-websocket

# when:
#  - condition: impl(ghcjs)
#    dependencies:
#      - ghcjs-base

executables:
  frontend:
    source-dirs:
      - src
      - ../shared/src
    main: Main.hs