os: 
  - linux
  - osx

language: nix

sudo: required

before_script:
  - sudo mount -o remount,exec,size=4G,mode=755 /run/user || true

script:
  - nix-env -if https://github.com/cachix/cachix/tarball/master --extra-substituters
    https://cachix.cachix.org --trusted-public-keys 'cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
    cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM= purehs.cachix.org-1:zkfNuhEOyL/EbMKiSdcJHUClo697yfna10ys3s7HbZ8='
  - cachix use purehs
  - nix-build -j auto --cores 0
