_install-nix: &install-nix
  - curl https://nixos.org/nix/install | sh

_cachix: &cachix
  - nix-env -if https://github.com/cachix/cachix/tarball/master --extra-substituters
    https://cachix.cachix.org --trusted-public-keys 'cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
    cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM= purehs.cachix.org-1:zkfNuhEOyL/EbMKiSdcJHUClo697yfna10ys3s7HbZ8='
  - cachix use purehs

before_install:
  - sudo mount -o remount,exec,size=4G,mode=755 /run/user || true

jobs:
  include:
    - os: linux
      install: &linux-install
        - *install-nix
        - source /home/travis/.nix-profile/etc/profile.d/nix.sh
        - *cachix
      script:
        - ./ghc npm run prod:backend
        - du -sh ./dist/ghc/build/*/ghc-*/backend-*/x/backend/opt/build/backend/backend

    - os: linux
      install:
        - *linux-install
      script:
        - ./ghcjs npm run prod:frontend
        - du -sh ./dist/site/frontend.js
        - du -sh ./dist/site/frontend.js.min
        - du -sh ./dist/site/frontend.js.min.gz

    - os: osx
      osx_image: xcode10.2
      language: generic
      install: &osx-install
        - *install-nix
        - source /Users/travis/.nix-profile/etc/profile.d/nix.sh
        - *cachix
      script:
        - ./ghc npm run prod:backend
        - du -sh ./dist/ghc/build/*/ghc-*/backend-*/x/backend/opt/build/backend/backend

    - os: osx
      osx_image: xcode10.2
      language: generic
      install:
        - *osx-install
      script:
        - nix-env -iA nixpkgs.pkgs.closurecompiler
        - ./ghcjs npm run prod:frontend
        - du -sh ./dist/site/frontend.js
        - du -sh ./dist/site/frontend.js.min
        - du -sh ./dist/site/frontend.js.min.gz