name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]  

    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v8
    - uses: cachix/cachix-action@v5
      with:
        name: purehs

    - name: build
      run: |
        nix-shell default.nix -A shells.ghc --run "cabal new-build backend"
        nix-shell default.nix -A shells.ghcjs --run "cabal new-build frontend --project-file=cabal-ghcjs.project"
